PermitRootLogin prohibit-password
PasswordAuthentication no
KbdInteractiveAuthentication no
PermitEmptyPasswords no
ChallengeResponseAuthentication no
AuthorizedKeysFile /root/.ssh/authorized_keys

MaxSessions 32
MaxStartups 16:30:64

AllowTcpForwarding yes
PermitTunnel no
GatewayPorts no
X11Forwarding no

Subsystem sftp internal-sftp

ClientAliveInterval 15
ClientAliveCountMax 4
TCPKeepAlive yes

UseDNS no

PrintMotd no
PrintLastLog no
Banner none
